version: '3.7'
services:
    db:
        image: mongo
        ports:
            - '27018:27017'
        restart: always
        volumes:
            - mongo-data:/data/db

    api:
        build: ./api
        command: >
            bash -c "npm install && node index.js"
        ports:
            - '8000:3001'
        volumes:
            - './api:/code'
        depends_on:
            - db


    web:
        build: ./frontend
        ports:
            - '3001:3000'
        command: >
            bash -c "npm install && npm run build && npm run start"
        depends_on:
            - api


volumes:
    mongo-data:
